# Generated by Django 5.1.5 on 2025-01-16 10:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Manzil nomi')),
                ('description', models.TextField(verbose_name="Manzil haqida ma'lumot")),
                ('image', models.ImageField(upload_to='destinations/', verbose_name='Manzil rasmi')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tur paketi nomi')),
                ('description', models.TextField(verbose_name="Tur haqida ma'lumot")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Davomiyligi (kunlarda)')),
                ('max_people', models.PositiveIntegerField(verbose_name='Maksimal odamlar soni')),
                ('transport_type', models.CharField(choices=[('BUS', 'Avtobus'), ('TRAIN', 'Poyezd'), ('PLANE', 'Samolyot')], max_length=5, verbose_name='Transport turi')),
                ('includes_hotel', models.BooleanField(default=True, verbose_name='Mehmonxona kiradi')),
                ('includes_food', models.BooleanField(default=True, verbose_name='Ovqat kiradi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.destination', verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Tur paketi',
                'verbose_name_plural': 'Tur paketlari',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.PositiveIntegerField(verbose_name='Odamlar soni')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('CONFIRMED', 'Tasdiqlangan'), ('CANCELLED', 'Bekor qilingan')], default='PENDING', max_length=10, verbose_name='Holat')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tourpackage', verbose_name='Tur paketi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
